version: "3.8"
services:
  rtmp:
    image: alfg/nginx-rtmp
    ports:
      - 17249:80
      - 1935:1935
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf.template

  auth_wsgi:
    image: roblobob/getlegit-streams-auth-wsgi
    build:
      context: ./auth
      dockerfile: Dockerfile

  auth_nginx:
    image: nginx:alpine
    volumes:
      - ./auth/nginx.conf:/etc/nginx/nginx.conf

